/* Copyright 2013 Brandon Edgren */

#ifndef COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_
#define COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_

const bool kDrawDebugData = true;

#endif  // COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_
