/* Copyright 2013 Brandon Edgren */

#ifndef COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_
#define COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_

#include <Box2D\Box2D.h>

const bool kDrawDebugData = true;
const int32 kPixelsPerMeter = 16;

#endif  // COSMICCOMBATPROJECT_COSMICCOMBATPROJECT_SETTINGS_H_
